package me.whereareiam.identica.testing.environment;

import me.whereareiam.anvil.api.scenario.ScenarioContext;
import me.whereareiam.anvil.environment.yggdrasil.YggdrasilMock;
import me.whereareiam.configura.Config;
import me.whereareiam.configura.Configura;
import me.whereareiam.configura.type.Format;
import me.whereareiam.identica.common.config.IdenticaModule;
import me.whereareiam.identica.common.config.defaults.EngineDefaults;
import me.whereareiam.identica.common.config.defaults.RoutingDefaults;
import me.whereareiam.identica.common.config.defaults.SettingsDefaults;
import me.whereareiam.identica.common.config.defaults.messages.MessagesDefaults;
import me.whereareiam.identica.common.config.defaults.provider.ProvidersDefaults;
import me.whereareiam.identica.model.config.Engine;
import me.whereareiam.identica.model.config.Messages;
import me.whereareiam.identica.model.config.Routing;
import me.whereareiam.identica.model.config.Settings;
import me.whereareiam.identica.model.config.provider.Providers;
import me.whereareiam.identica.feature.recognition.config.RecognitionSettings;
import me.whereareiam.identica.feature.recognition.config.defaults.RecognitionSettingsDefaults;
import me.whereareiam.identica.feature.sentinel.config.defaults.SentinelSettingsDefaults;
import me.whereareiam.identica.feature.sentinel.model.config.SentinelSettings;
import me.whereareiam.identica.model.routing.attempt.RoutingAttemptPolicy;
import me.whereareiam.identica.provider.credential.config.CredentialSettings;
import me.whereareiam.identica.provider.credential.config.defaults.CredentialSettingsDefaults;
import me.whereareiam.identica.provider.premium.config.PremiumSettings;
import me.whereareiam.identica.type.pipeline.journey.JourneyMode;
import me.whereareiam.identica.type.pipeline.journey.JourneyPolicy;
import me.whereareiam.identica.type.routing.RoutingRetryMode;

import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.time.Duration;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * The configuration files one test proxy starts with. Each file is Identica's own model, filled with its
 * defaults and changed where the test network differs, then written as the plugin writes it. A test changes
 * the models through {@link Identica#configure()}; a file it leaves out is generated by the plugin itself.
 */
public final class ProxyConfiguration {
	/** Written as the plugin writes them, including Identica's own value types. */
	private static final Configura CONFIGURA = Config.builder().format(Format.YAML).module(new IdenticaModule()).build();
	private static final int DEBUG_LEVEL = 3;

	private static final String ENGINE = "engine.yml";
	private static final String ROUTING = "routing.yml";
	private static final String SETTINGS = "settings.yml";
	private static final String MESSAGES = "messages.yml";
	private static final String PROVIDERS = "providers/providers.yml";
	private static final String PREMIUM = "providers/Premium/settings.yml";
	private static final String CREDENTIAL = "providers/Credential/settings.yml";
	private static final String SENTINEL = "features/sentinel/settings.yml";
	private static final String RECOGNITION = "features/recognition/settings.yml";

	private final String name;
	private final Map<String, Object> documents = new LinkedHashMap<>();
	private final Map<String, String> unreadable = new LinkedHashMap<>();

	ProxyConfiguration(
			String name,
			JourneyMode mode,
			JourneyPolicy policy,
			Set<Provider> enabled,
			boolean entrypoints,
			boolean autoSelectSingleProvider,
			String step,
			String complete,
			YggdrasilMock yggdrasil
	) {
		this.name = name;
		documents.put(ENGINE, defaultEngine(mode, policy, autoSelectSingleProvider));
		documents.put(ROUTING, defaultRouting(step, complete));
		documents.put(SETTINGS, defaultSettings());
		documents.put(PROVIDERS, defaultProviders(enabled, entrypoints));
		documents.put(PREMIUM, defaultPremium(yggdrasil));
	}

	/**
	 * Returns the name of the proxy these files are for, such as {@link IdenticaNetwork#PROXY_B}, for a
	 * change that only one proxy of a cluster gets.
	 */
	public String name() {
		return name;
	}

	public Engine engine() {
		return (Engine) documents.get(ENGINE);
	}

	public Routing routing() {
		return (Routing) documents.get(ROUTING);
	}

	public Settings settings() {
		return (Settings) documents.get(SETTINGS);
	}

	public Providers providers() {
		return (Providers) documents.get(PROVIDERS);
	}

	/**
	 * Returns Identica's messages, starting from its defaults. The proxy only gets a messages file from the test
	 * once a test asks for them.
	 */
	public Messages messages() {
		return (Messages) documents.computeIfAbsent(MESSAGES, ignored -> new MessagesDefaults().supply(new Messages()));
	}

	/**
	 * Returns the Credential provider's settings, starting from its defaults. The proxy only gets this file from
	 * the test once a test asks for it.
	 */
	public CredentialSettings credential() {
		return (CredentialSettings) documents.computeIfAbsent(CREDENTIAL, ignored -> new CredentialSettingsDefaults().supply(new CredentialSettings()));
	}

	/**
	 * Returns the sentinel feature's shared settings, starting from their defaults. The proxy only gets this file
	 * from the test once a test asks for it.
	 */
	public SentinelSettings sentinel() {
		return (SentinelSettings) documents.computeIfAbsent(SENTINEL, ignored -> new SentinelSettingsDefaults().supply(new SentinelSettings()));
	}

	/**
	 * Returns the recognition feature's shared settings, starting from their defaults. The proxy only gets this
	 * file from the test once a test asks for it.
	 */
	public RecognitionSettings recognition() {
		return (RecognitionSettings) documents.computeIfAbsent(RECOGNITION, ignored -> new RecognitionSettingsDefaults().supply(new RecognitionSettings()));
	}

	/**
	 * Adds or replaces a file with one of Identica's models.
	 *
	 * @param path path inside Identica's data directory, such as {@code persistence.yml}
	 * @param document model to write
	 */
	public void put(String path, Object document) {
		unreadable.remove(path);
		documents.put(path, document);
	}

	/**
	 * Leaves a file out, so the plugin generates it as on a new installation.
	 */
	public void omit(String path) {
		documents.remove(path);
		unreadable.remove(path);
	}

	/**
	 * Writes a file with content Identica cannot read, to see how it starts on a broken configuration.
	 */
	public void corrupt(String path, String content) {
		documents.remove(path);
		unreadable.put(path, content);
	}

	/**
	 * Reads a file as the running proxy left it, into one of Identica's models.
	 *
	 * @param anvil running network
	 * @param path path inside Identica's data directory, such as {@code providers/providers.yml}
	 * @param type model to read the file as
	 */
	public static <T> T generated(ScenarioContext anvil, String path, Class<T> type) {
		Path dataDirectory = anvil.processes().proxy(anvil.definition().getEntrypoint()).workDirectory().resolve(IdenticaNetwork.DATA);
		return CONFIGURA.read(dataDirectory.resolve(path), type);
	}

	/**
	 * Returns the written files by path inside Identica's data directory.
	 */
	Map<String, String> files() {
		Map<String, String> files = new LinkedHashMap<>();
		documents.forEach((path, document) -> files.put(path, write(document)));
		files.putAll(unreadable);

		return files;
	}

	private static Engine defaultEngine(JourneyMode mode, JourneyPolicy policy, boolean autoSelectSingleProvider) {
		Engine engine = new EngineDefaults().supply(new Engine());
		Engine.Scenarios scenarios = engine.getScenarios();
		for (Engine.Scenario scenario : List.of(scenarios.getAuthentication(), scenarios.getRegistration())) {
			scenario.setJourneyMode(mode);
			scenario.setJourneyPolicy(policy);
		}
		scenarios.getRegistration().setAutoSelectSingleProvider(autoSelectSingleProvider);

		return engine;
	}

	/**
	 * Players stay on the step target while a step waits for them and reach the completion target when they are
	 * done; a blank target leaves them where they are. Completion routing retries until the player arrives.
	 */
	private static Routing defaultRouting(String step, String complete) {
		Routing routing = new RoutingDefaults().supply(new Routing());
		routing.getDefaults().getStep().setTarget(step);

		RoutingAttemptPolicy untilReached = new RoutingAttemptPolicy();
		untilReached.setMode(RoutingRetryMode.UNTIL_REACHED);
		untilReached.setRetryDelay(Duration.ofSeconds(1));
		untilReached.setConsumeOnReached(true);
		routing.getDefaults().getComplete().setTarget(complete);
		routing.getDefaults().getComplete().setAttempts(untilReached);
		routing.getScenarios().clear();

		return routing;
	}

	private static Settings defaultSettings() {
		Settings settings = new SettingsDefaults().supply(new Settings());
		settings.setLevel(DEBUG_LEVEL);

		return settings;
	}

	private static Providers defaultProviders(Set<Provider> enabled, boolean entrypoints) {
		Providers providers = new ProvidersDefaults().supply(new Providers());
		Map<String, Providers.ProviderEntry> known = providers.getProviders().stream()
				.collect(Collectors.toMap(Providers.ProviderEntry::getId, entry -> entry));

		List<Providers.ProviderEntry> entries = new ArrayList<>();
		for (Provider provider : Provider.values()) {
			Providers.ProviderEntry entry = known.get(provider.getId());
			entry.setEnabled(enabled.contains(provider));
			entry.setPriority(provider.getPriority());
			entry.setEntrypoints(entrypoints ? List.of(provider.getEntrypoint()) : List.of());
			entries.add(entry);
		}
		providers.setProviders(entries);

		return providers;
	}

	/**
	 * Premium asks the network's stand-in, not Mojang, whether a username is premium, and does not cache the answer.
	 */
	private static PremiumSettings defaultPremium(YggdrasilMock yggdrasil) {
		PremiumSettings settings = new PremiumSettings();
		settings.getLookup().setProfileEndpoint(yggdrasil.profileLookup() + "%s");
		settings.getLookup().setCacheTtl(Duration.ZERO);

		return settings;
	}

	private static String write(Object document) {
		return new String(CONFIGURA.writeBytes(document), StandardCharsets.UTF_8);
	}
}
